# --- OpenAPI Specification for FitTrack API ---
# Specification version
openapi: 3.0.0

# --- Information about API ---
info:
  title: FitTrack API
  description: API for the FitTrack web application for tracking nutrition.
  version: "1.0.0"

# --- Servers ---
# Specify the base path for all our endpoints.
servers:
  - url: /api
    description: Mocked server

# --- Global components ---
components:
  # --- Schemas ---
  securitySchemes:
    # --- JWT Bearer Authentication Scheme ---
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT Authorization header using the Bearer scheme."

# --- Description of endpoints ---
paths:
  # --- Endpoints for /auth ---
  /auth/register:
    post:
      $ref: "./endpoints/auth.yaml#/components/register"

  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/components/login"

  /auth/refresh-token:
    post:
      $ref: "./endpoints/auth.yaml#/components/refreshToken"

  # --- Endpoints for /food-logs ---
  /food-logs:
    get:
      $ref: "./endpoints/food-logs.yaml#/components/getFoodLogs"
    post:
      $ref: "./endpoints/food-logs.yaml#/components/createFoodLog"

  # --- Endpoints for /food-logs/{date} ---

  /food-logs/{date}:
    get:
      $ref: "./endpoints/food-logs.yaml#/components/getFoodLogsByDate"

  # --- Endpoints for /food-logs/{id} ---

  /food-logs/{id}:
    put:
      $ref: "./endpoints/food-logs.yaml#/components/updateFoodLog"

    delete:
      $ref: "./endpoints/food-logs.yaml#/components/deleteFoodLog"

  # --- Endpoints for /water-logs ---
  /water-logs:
    post:
      $ref: "./endpoints/water-logs.yaml#/components/createWaterLog"

  /water-logs/{date}:
    get:
      $ref: "./endpoints/water-logs.yaml#/components/getWaterLogByDate"

  /water-logs/{id}:
    put:
      $ref: "./endpoints/water-logs.yaml#/components/updateWaterLog"

  # --- Endpoints for /user ---
  /user:
    get:
      $ref: "./endpoints/user.yaml#/components/getUser"
    put:
      $ref: "./endpoints/user.yaml#/components/updateUser"
  /user/weight:
    post:
      $ref: "./endpoints/weight-logs.yaml#/components/addWeightLog"
  /user/weight/{id}:
    put:
      $ref: "./endpoints/weight-logs.yaml#/components/updateWeightLog"
    delete:
      $ref: "./endpoints/weight-logs.yaml#/components/deleteWeightLog"

  # --- Open Food Facts Endpoints ---
  /cgi/search.pl:
    get:
      tags:
        - Open Food Facts
      $ref: "./endpoints/open-food-facts.yaml#/components/searchProducts"

  /api/v2/product/{barcode}:
    get:
      tags:
        - Open Food Facts
      $ref: "./endpoints/open-food-facts.yaml#/components/getProductByBarcode"
